### ISSUE TITLE
我这边返回的数据是多层嵌套的数据，这边能不能开个口子用来处理数据

### ISSUE THREAD

**Issue by Amdeo** [zclzone/qs-admin#4]
![image](https://user-images.githubusercontent.com/30571182/218609000-bcf83d64-28bd-4ceb-9ef6-c69fb249b200.png)

**Comment by zclzone** [comment]
你可以给getData包一层promise，而不是直接请求，类似下面这样
async function getData(params) {
  const { data } = await api.getData(params)
  
  const resolveData = {}
  resolveData.pageData = ...
  resolveData.total = ...

  return new Promise((resolve,reject) => {
    return resolve({data: resolveData})
  }) 
}

**Comment by Amdeo** [comment]
好的，感谢帮助
