### ISSUE TITLE
开启多个面页后，慢慢变得很卡，chrome占用的1G内存，可能存在内存泄露。

### ISSUE THREAD

**Issue by AdamvvYau** [zclzone/qs-admin#7]
开启多个面页后，慢慢变得很卡，chrome占用的1G内存，可能存在内存泄露。

**Comment by zclzone** [comment]
> 开启多个面页后，慢慢变得很卡，chrome占用的1G内存，可能存在内存泄露。

哪个页面？可以截图看下，我这边不管怎么试都没超过30M
